config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ptracesecurity/pytest-example:
      branch: master
      repo: https://github.com/ptracesecurity/pytest-example
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ptracesecurity/pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-mustard-wallaby.sh
        container: qc.acc_sickly-turquoise-mau
  QC.Doc:
    repos:
      github.com/ptracesecurity/pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-scarlet-uguisu.sh
        container: qc.doc_whiny-brass-snail
      github.com/ptracesecurity/pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-turquoise-hedgehog.sh
        container: qc.doc_wheezy-olive-spider
      github.com/ptracesecurity/pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-rose-anteater.sh
        container: qc.doc_ugly-silver-tortoise
  QC.Lic:
    repos:
      github.com/ptracesecurity/pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-black-boar.sh
        container: qc.lic_randy-plum-robin
  QC.Sec:
    repos:
      github.com/ptracesecurity/pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-red-cow.sh
        container: qc.sec_sickly-olive-spitz
  QC.Sty:
    repos:
      github.com/ptracesecurity/pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-tomato-angelfish.sh
        container: qc.sty_flimsy-cobalt-zorse
      github.com/ptracesecurity/pytest-example jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cerise-devil.sh
        container: qc.sty_scummy-platinum-orangutan
  QC.Uni:
    repos:
      github.com/ptracesecurity/pytest-example commands:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-buff-sparrow.sh
        container: qc.uni_queasy-salmon-burmese
  QC.Ver:
    repos:
      github.com/ptracesecurity/pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-violet-stoat.sh
        container: qc.ver_pretty-rose-robin
timeout: 5400
