config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ptracesecurity/pytest-example:
      branch: master
      repo: https://github.com/ptracesecurity/pytest-example
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ptracesecurity/pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-platinum-cassowary.sh
        container: qc.acc_woozy-smalt-dogfish
  QC.Doc:
    repos:
      github.com/ptracesecurity/pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ecru-chow.sh
        container: qc.doc_thirsty-olive-owl
      github.com/ptracesecurity/pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-bistre-angelfish.sh
        container: qc.doc_craggy-azure-mole
      github.com/ptracesecurity/pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-periwinkle-bulldog.sh
        container: qc.doc_pasty-amber-chipmunk
  QC.Lic:
    repos:
      github.com/ptracesecurity/pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-mustard-toad.sh
        container: qc.lic_clammy-cream-argentino
  QC.Sec:
    repos:
      github.com/ptracesecurity/pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-chartreuse-affenpinscher.sh
        container: qc.sec_fuzzy-flax-spitz
  QC.Sty:
    repos:
      github.com/ptracesecurity/pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.silly-thistle-serval.sh
        container: qc.sty_geeky-sepia-spider
      github.com/ptracesecurity/pytest-example jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-razzmatazz-monkey.sh
        container: qc.sty_zippy-malachite-donkey
  QC.Uni:
    repos:
      github.com/ptracesecurity/pytest-example pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-champagne-chihuahua.sh
        container: qc.uni_hasty-dandelion-owl
  QC.Ver:
    repos:
      github.com/ptracesecurity/pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ruby-clam.sh
        container: qc.ver_shabby-puce-newfoundland
timeout: 5400
