config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ptracesecurity/pytest-example:
      branch: master
      repo: https://github.com/ptracesecurity/pytest-example
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ptracesecurity/pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-scarlet-fousek.sh
        container: qc.acc_queasy-aquamarine-shrew
  QC.Doc:
    repos:
      github.com/ptracesecurity/pytest-example find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-persimmon-kiwi.sh
        container: qc.doc_lumpy-asparagus-wrasse
      github.com/ptracesecurity/pytest-example git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ultramarine-fowl.sh
        container: qc.doc_lovely-gold-discus
      github.com/ptracesecurity/pytest-example markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-orchid-spider.sh
        container: qc.doc_hilly-white-gecko
  QC.Lic:
    repos:
      github.com/ptracesecurity/pytest-example licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-linen-baboon.sh
        container: qc.lic_gloppy-harlequin-pinscher
  QC.Sec:
    repos:
      github.com/ptracesecurity/pytest-example bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-red-markhor.sh
        container: qc.sec_seedy-amber-dachshund
  QC.Sty:
    repos:
      github.com/ptracesecurity/pytest-example flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-xanthic-monster.sh
        container: qc.sty_grumpy-gamboge-barb
      github.com/ptracesecurity/pytest-example jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-crimson-oriole.sh
        container: qc.sty_skinny-eggplant-fousek
  QC.Uni:
    repos:
      github.com/ptracesecurity/pytest-example pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-firebrick-toad.sh
        container: qc.uni_jumpy-amethyst-hamster
  QC.Ver:
    repos:
      github.com/ptracesecurity/pytest-example get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-sapphire-blue.sh
        container: qc.ver_scummy-silver-ant
timeout: 5400
